### ISSUE TITLE
[Documentation request] How do you test this on mac please

### ISSUE THREAD

**Issue by neiljaywarner** [mwaylabs/flutter-managed-configuration#11]
How do you test this on mac please? trying simplemdm, defaults write, no luck so far

**Comment by lucygeneric** [comment]
@neiljaywarner did you get this working? It's hard to tell if this works on iOs at all?

**Comment by neiljaywarner** [comment]
@lucygeneric  it is fine on ios it is fine on mac with simplemdm, to use it with mac with intune i had to write custom swift code :(

**Comment by danielkono** [comment]
Apple provides for managed app configuration same code for both platforms. With 1.0.0 we migrated the iOS code to run also on MacOS by using the [darwin](https://docs.flutter.dev/packages-and-plugins/developing-packages#shared-ios-and-macos-implementations). The test setup is for us quite simple because we develop our own mdm solutions. 
You can create a free Account at [https://live.relution.io](https://live.relution.io) (it's free up to five devices).

* [enroll macOS](https://hub.relution.io/en/docs/apple-macos/enrollment/manual-enrollment/)
* [add config](https://hub.relution.io/en/docs/apple-macos/policies/overview/)
* [managed app config](https://hub.relution.io/en/docs/apple-macos/policies/managed-app-configuration/)

Could you please share some information about your MacOS device?

**Comment by neiljaywarner** [comment]
It's just that Microsoft InTune works differently.

The keys go directly into userdefaults.standard not onto a subdictionary

....sent from my phone

**Comment by danielkono** [comment]
ok, but then once could use the SharedPreferences package to get the NSUserDefaults. Pay attention that it adds per default ".flutter" to all keys. -> https://pub.dev/packages/shared_preferences#migration-and-prefixes.

**Comment by neiljaywarner** [comment]
I tried that too and it does not work because it locks ot down to
persistent domain bundle id of the app

....sent from my phone

**Comment by danielkono** [comment]
Unfortunately we cannot provide custom solutions for each MDM provider. This package implements the process how both Platforms (darwin and Android) described in their docu.  Feel free to create a PR
