### ISSUE TITLE
Still maintained/updated?

### ISSUE THREAD

**Issue by AdrianDev0** [mwaylabs/flutter-managed-configuration#4]
Hello,

thanks for your awesome library.
I was wondering, if it is still maintained, since there hasn't been an update in a year?

Kind regards

**Comment by danielkono** [comment]
Hi,

yes. This package is used by our products and therefor it will be maintained if needed. But at the moment no bugs/feature request to be done or breaking changes in the native API to adapt.

When something occurs please provide a new issue :)

**Comment by sbatezat** [comment]
@danielkono maintenance is needed.
On my new Flutter project, I can't use this library. 

Error I've got :

> * What went wrong:
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
> The following dependencies do not satisfy the required version:
> project ':managed_configurations' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

It's related to https://github.com/mwaylabs/flutter-managed-configuration/issues/5 and may be fixed by https://github.com/mwaylabs/flutter-managed-configuration/pull/3

Given that the PR has been created more than one years ago, the question of this thread seems very relevant.
